### PR TITLE
fixes refspecs for a few plugins by updating them to the most recent …

### LINKED ISSUE #364: Plugins have the wrong refspec(s) in packages.json
I think think the `c9.ide.collab` plugin's refspec is wrong here: https://github.com/z3cka/core/commit/5f45ea38f422160a0030c5ef8d1efb19231bc78c#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

I changed it back to #54aa1cbee0, ran the install-sdk.sh and it grabbed the latest version of the collab plugin. While prepping a PR, I just found 3 more plugins with bad refspecs

This was causing `/static/plugins/c9.ide.collab/notifications/bubble.js` to 404 on first launch of c9.

#311 had a similar issue.

I'm not sure if `packages.json` is to be edited manually; please let me know if there is a better way to do this.

I just found 3 more plugins with bad refspecs
* `c9.ide.language`
* `c9.ide.language.javascript.eslint`
* `c9.ide.run.debug`

Will work up a PR when I can get a functioning build.

### PR DESCRIPTION
**Pull request by z3cka**
…commit

resolves #364

### CODE REVIEW

**Comment by nightwing** [comment]
There was a bug in the script updating references and this pr helped us to identify and fix it. Thanks!
Please confirm that this issue is fixed now.

**Comment by z3cka** [comment]
Looks like `c9.ide.language.javascript.eslint` version got fixed by: https://github.com/c9/core/commit/b28fbcd20cd32c901d202aa6c2cc64196d5d9d65#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R69

Will rebase and update PR.

**Comment by z3cka** [comment]
running a new build via https://hub.docker.com/r/z3cka/c9/builds/ to test... will report back.

**Comment by z3cka** [comment]
Woot! Build successful and the app is running great! @nightwing is there any documentation on how this script works? Is it realated to this: https://github.com/c9/c9.ide.language.javascript.eslint/commit/342a071123631bd5d9d067e20de0f51acbc83ba5 commit? 

Thanks for the great work!

**Comment by nightwing** [comment]
@z3cka it's an internal script that syncs code between monorepo and plugins, it pushed to c9/core but couldn't push to other repositories.

**Comment by z3cka** [comment]
neat. @nightwing any documentation on how that works?

**Comment by nightwing** [comment]
no documentation, it's an internal script.

**Pull request closed without merging**
