### PR TITLE
Adding a CSS class to identify core panel buttons

### PR DESCRIPTION
**Pull request by jumbojett**
This will allow themes to identify core panel buttons and style them further.

### CODE REVIEW

**Comment by nightwing** [comment]
How exactly are you going to use these classes?
Maybe it would be better to automatically set classes based on panel name in
https://github.com/c9/core/blob/master/plugins/c9.ide.panels/panel.js#L25?

**Comment by jumbojett** [comment]
@nightwing To display a meaningful font icon preceding the text. This makes both buttons consistent with other panel buttons in C9 that have a class.

**Comment by jumbojett** [comment]
> Maybe it would be better to automatically set classes based on panel name in
:+1: I agree - That would be better. How would you like to proceed?

**Comment by nightwing** [comment]
cc @javruben

**Comment by javruben** [comment]
@nightwing I like the auto class setting, but I'm concerned about future multi-lingual efforts. What process are you thinking about for the auto-setting?

**Comment by nightwing** [comment]
i18n could use automatic id too something like "PanelButton:" + panel.name. 
But I merged as is for now, we can change it to automatic later

**Comment by jumbojett** [comment]
Ty fellas :+1:  @nightwing @javruben

**Pull request closed without merging**
