### PR TITLE
Added reload button to plugin manager

### PR DESCRIPTION
**Pull request by invokr**
The debug mode is nice if you want to actually debug, but applying a new iteration of your plugin with c9 spamming your dev-console with a million messages isn't really great.

Just reloading the plugin via the managers feels more natural and also works when you develop on core plugins (such as the plugin manager :)).

### CODE REVIEW

**Comment by nightwing** [comment]
This is great, and very useful:)
I see the new [reload function](https://github.com/c9/core/pull/51/files#diff-0bf7ca2fe9d4bcf719825e6bc283945fR612) is very similar to the [reloadPackage function](https://github.com/c9/core/blob/9cc2265cb1fe210b6bdfb9eee9a5056637eacb29/plugins/c9.ide.plugins/debug.js#L190) from debug, is it possible to use that to not have duplicated code?
Were you editing this file with cloud9? Looks like we need to move trim trailing whitespace setting to the project settings to keep it consistent and not cause unnecessary merge conflicts.
Good point about debug mode, we'll update it to show socket messages only if debug=3

**Comment by invokr** [comment]
I was editing it with cloud9, I always use "trim whitespaces" so I though nothing of it.

Regarding debug: I was under the impression that the plugin should be used in the sdk / dev environment only (https://github.com/c9/core/blob/9cc2265cb1fe210b6bdfb9eee9a5056637eacb29/plugins/c9.ide.plugins/debug.js#L35), so I copied the function.

Should I rather import the debug plugin the manager?

**Comment by nightwing** [comment]
> Should I rather import the debug plugin the manager?

Yes please. I think using it from manager is ok because debug plugin is always loaded to allow handling  of `debug=2` flag in url.

**Comment by invokr** [comment]
Okay, let me know if there are any other issues.

**Comment by nightwing** [comment]
Thanks i've merged this but unfortunately due to an error in syncing script your commit ended up as https://github.com/c9/core/commit/2b29604421205096c4dfc7bae82bcef8eaec6803

One possible improvement for this is to allow reloading of multiple selected plugins and whole packages.

**Pull request closed without merging**
